const router = require("express").Router();
const pool = require("../config/db");

// GET /api/products — Get all products (active only by default)
router.get("/", async (req, res, next) => {
  try {
    const includeInactive = req.query.include_inactive === 'true';
    const whereClause = includeInactive ? '' : 'WHERE p.is_active = TRUE';

    const query = `
      SELECT p.*, c.category_name, s.supplier_name 
      FROM products p
      LEFT JOIN categories c ON p.category_id = c.category_id
      LEFT JOIN suppliers s ON p.supplier_id = s.supplier_id
      ${whereClause}
      ORDER BY p.product_id
    `;
    const result = await pool.query(query);
    res.json(result.rows);
  } catch (err) {
    next(err);
  }
});

// GET /api/products/search — Search by barcode, SKU, or name
router.get("/search", async (req, res, next) => {
  try {
    const { q } = req.query;
    if (!q || !q.trim()) {
      return res.json([]);
    }

    const includeInactive = req.query.include_inactive === 'true';
    const activeFilter = includeInactive ? '' : 'AND p.is_active = TRUE';
    
    const query = `
      SELECT p.*, c.category_name, s.supplier_name 
      FROM products p
      LEFT JOIN categories c ON p.category_id = c.category_id
      LEFT JOIN suppliers s ON p.supplier_id = s.supplier_id
      WHERE (
          p.barcode = $1
          OR p.sku = $1
          OR p.product_name ILIKE '%' || $1 || '%'
      )
      ${activeFilter}
      ORDER BY
          CASE WHEN p.barcode = $1 THEN 0
               WHEN p.product_name ILIKE $1 || '%' THEN 1
               ELSE 2 END,
          p.product_name
      LIMIT 20
    `;
    const result = await pool.query(query, [q.trim()]);
    res.json(result.rows);
  } catch (err) {
    next(err);
  }
});

// GET /api/products/:id — Get single product
router.get("/:id", async (req, res, next) => {
  try {
    const { id } = req.params;
    const query = `
      SELECT p.*, c.category_name, s.supplier_name 
      FROM products p
      LEFT JOIN categories c ON p.category_id = c.category_id
      LEFT JOIN suppliers s ON p.supplier_id = s.supplier_id
      WHERE p.product_id = $1
    `;
    const result = await pool.query(query, [id]);

    if (result.rows.length === 0) {
      return res.status(404).json({ error_code: "NOT_FOUND", error: "Product not found" });
    }
    res.json(result.rows[0]);
  } catch (err) {
    next(err);
  }
});

// POST /api/products — Create new product (SKU auto-generated by trigger)
router.post("/", async (req, res, next) => {
  try {
    const { product_name, description, purchase_price, selling_price, stock_quantity, category_id, supplier_id, barcode } = req.body;

    // Validations
    if (!product_name || !product_name.trim() || purchase_price === undefined || selling_price === undefined || !category_id || !supplier_id) {
      return res.status(400).json({ error_code: "REQUIRED_FIELDS", error: "product_name, purchase_price, selling_price, category_id, and supplier_id are required" });
    }

    if (purchase_price <= 0) {
      return res.status(400).json({ error_code: "NEGATIVE_VALUE", error: "purchase_price must be greater than zero" });
    }

    if (selling_price <= 0) {
      return res.status(400).json({ error_code: "NEGATIVE_VALUE", error: "selling_price must be greater than zero" });
    }

    if (selling_price < purchase_price) {
      return res.status(400).json({ error_code: "PRICE_LOGIC_ERROR", error: "selling_price cannot be less than purchase_price" });
    }

    const qty = stock_quantity !== undefined ? stock_quantity : 0;
    if (qty < 0) {
      return res.status(400).json({ error_code: "NEGATIVE_VALUE", error: "stock_quantity cannot be negative" });
    }

    const result = await pool.query(
      `INSERT INTO products (product_name, description, purchase_price, selling_price, stock_quantity, category_id, supplier_id, barcode) 
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING *`,
      [product_name.trim(), description || null, purchase_price, selling_price, qty, category_id, supplier_id, barcode || null]
    );
    res.status(201).json({ message: "Product created successfully", data: result.rows[0] });
  } catch (err) {
    next(err);
  }
});

// PUT /api/products/ — Handle missing ID
router.put("/", (req, res, next) => {
  res.status(400).json({ error_code: "ID_REQUIRED", error: "Product ID is required" });
});

// PUT /api/products/:id — Update product (sku is silently ignored)
router.put("/:id", async (req, res, next) => {
  try {
    const { id } = req.params;

    // 1. Fetch existing product
    const checkResult = await pool.query("SELECT * FROM products WHERE product_id = $1", [id]);
    if (checkResult.rows.length === 0) {
      return res.status(404).json({ error_code: "NOT_FOUND", error: "Product not found" });
    }
    const existing = checkResult.rows[0];

    // 2. Merge existing data with new data (sku is silently ignored)
    const { sku, ...body } = req.body;
    
    if (body.product_name !== undefined && !body.product_name.trim()) {
       return res.status(400).json({ error_code: "REQUIRED_FIELDS", error: "product_name cannot be empty" });
    }
    
    const product_name = body.product_name !== undefined ? body.product_name.trim() : existing.product_name;
    const description = body.description !== undefined ? body.description : existing.description;
    const purchase_price = body.purchase_price !== undefined ? body.purchase_price : existing.purchase_price;
    const selling_price = body.selling_price !== undefined ? body.selling_price : existing.selling_price;
    const stock_quantity = body.stock_quantity !== undefined ? body.stock_quantity : existing.stock_quantity;
    const category_id = body.category_id !== undefined ? body.category_id : existing.category_id;
    const supplier_id = body.supplier_id !== undefined ? body.supplier_id : existing.supplier_id;
    const barcode = body.barcode !== undefined ? (body.barcode || null) : existing.barcode;
    const is_active = body.is_active !== undefined ? body.is_active : existing.is_active;

    // 3. Validations on merged data
    if (purchase_price <= 0) {
      return res.status(400).json({ error_code: "NEGATIVE_VALUE", error: "purchase_price must be greater than zero" });
    }
    if (selling_price <= 0) {
      return res.status(400).json({ error_code: "NEGATIVE_VALUE", error: "selling_price must be greater than zero" });
    }
    if (selling_price < purchase_price) {
      return res.status(400).json({ error_code: "PRICE_LOGIC_ERROR", error: "selling_price cannot be less than purchase_price" });
    }
    if (stock_quantity < 0) {
      return res.status(400).json({ error_code: "NEGATIVE_VALUE", error: "stock_quantity cannot be negative" });
    }

    // 4. Check barcode uniqueness (if provided and changed)
    if (barcode && barcode !== existing.barcode) {
      const barcodeCheck = await pool.query(
        "SELECT product_id FROM products WHERE barcode = $1 AND product_id != $2",
        [barcode, id]
      );
      if (barcodeCheck.rows.length > 0) {
        return res.status(400).json({ error_code: "DUPLICATE_BARCODE", error: "هذا الباركود مستخدم لمنتج آخر." });
      }
    }

    // 5. Update Database
    const result = await pool.query(
      `UPDATE products 
       SET product_name = $1, description = $2, purchase_price = $3, selling_price = $4, 
           stock_quantity = $5, category_id = $6, supplier_id = $7, barcode = $8, is_active = $9
       WHERE product_id = $10 RETURNING *`,
      [product_name, description, purchase_price, selling_price, stock_quantity, category_id, supplier_id, barcode, is_active, id]
    );

    res.json({ message: "Product updated successfully", data: result.rows[0] });
  } catch (err) {
    next(err);
  }
});

// POST /api/products/:id/restock — Restock using DB function (WAC calculation)
router.post("/:id/restock", async (req, res, next) => {
  try {
    const { id } = req.params;
    const { quantity, purchase_price, selling_price } = req.body;

    // Validate inputs
    if (!quantity || quantity <= 0) {
      return res.status(400).json({ error_code: "NEGATIVE_VALUE", error: "Restock quantity must be positive" });
    }
    if (!purchase_price || purchase_price <= 0) {
      return res.status(400).json({ error_code: "NEGATIVE_VALUE", error: "Purchase price must be positive" });
    }

    // Check product exists and is active
    const check = await pool.query("SELECT is_active FROM products WHERE product_id = $1", [id]);
    if (check.rows.length === 0) {
      return res.status(404).json({ error_code: "NOT_FOUND", error: "Product not found" });
    }
    if (!check.rows[0].is_active) {
      return res.status(400).json({ error_code: "INACTIVE_PRODUCT", error: "Cannot restock an inactive product." });
    }

    // Call restock_product() — single source of truth
    const result = await pool.query(
      "SELECT * FROM restock_product($1, $2, $3, $4)",
      [id, quantity, purchase_price, selling_price || null]
    );

    res.json({
      message: "تم إعادة التخزين بنجاح",
      data: result.rows[0],
      added_quantity: quantity
    });
  } catch (err) {
    next(err);
  }
});

// DELETE /api/products/ — Handle missing ID
router.delete("/", (req, res, next) => {
  res.status(400).json({ error_code: "ID_REQUIRED", error: "Product ID is required" });
});

// DELETE /api/products/:id — Soft Delete (Deactivate)
router.delete("/:id", async (req, res, next) => {
  try {
    const { id } = req.params;
    const result = await pool.query(
      "UPDATE products SET is_active = FALSE WHERE product_id = $1 AND is_active = TRUE RETURNING *",
      [id]
    );
    if (result.rows.length === 0) {
      return res.status(404).json({ error_code: "NOT_FOUND", error: "Product not found or already inactive" });
    }
    res.json({ message: "Product deactivated successfully", data: result.rows[0] });
  } catch (err) {
    next(err);
  }
});

// PUT /api/products/:id/activate — Reactivate product
router.put("/:id/activate", async (req, res, next) => {
  try {
    const { id } = req.params;
    const result = await pool.query(
      "UPDATE products SET is_active = TRUE WHERE product_id = $1 AND is_active = FALSE RETURNING *",
      [id]
    );
    if (result.rows.length === 0) {
      return res.status(404).json({ error_code: "NOT_FOUND", error: "Product not found or already active" });
    }
    res.json({ message: "Product activated successfully", data: result.rows[0] });
  } catch (err) {
    next(err);
  }
});

module.exports = router;
